### PR TITLE
JI-5476 replace 10 or more consecutive underscores with 9 in task des…

### PR DESCRIPTION
**Pull request by makmentins**
…cription

### CODE REVIEW

**Comment by makmentins** [comment]
This is a fix for the same problem that was fixed for clues here [https://github.com/otacke/h5p-crossword/pull/90](https://github.com/otacke/h5p-crossword/pull/90). It might be that a scenario where user inputs 10 or more consecutive underscores in the description is even less likely than for clues, but since this problem is reproducible with the description as well, we should probably add a fix for that. I believe that the reason why underscores are used as the fill in placeholder, is because of the way LRS's display the descriptions, so a fix on content level was chosen.

**Comment by otacke** [comment]
@makmentins Will need to look at this later, not at my desk currently. I don't mind a fix on the content type level, but would prefer to use a UUID or similar as the placholder, potentially even provided via H5PIntegration, to rule out such conflicts. If content types need to be changed anyway ...

**Comment by otacke** [comment]
I have merged this, but having to have a similar solution in every "fill-in" activity is not desirable. Too much complexity which is not documented and developers need to think of. I still suggest to find a different placeholder (e.g. a UUID) in general.

**Comment by otacke** [comment]
@makmentins "I believe that the reason why underscores are used as the fill in placeholder, is because of the way LRS's display the descriptions, so a fix on content level was chosen." => Why don't you simply add the same workaround in [https://github.com/h5p/h5p-php-library/blob/master/js/h5p-event-dispatcher.js No need to c](https://github.com/h5p/h5p-php-library/blob/master/js/h5p-event-dispatcher.js#L225-L254) Just check for `instance of XAPIEvent` and replace the description properties (plural, the language is not fixed to `en-US`) accordingly. No need to add complexity to every content type.

**Pull request merged**
