### PR TITLE
GitHub actions test 6

### PR DESCRIPTION
**Pull request by GuiLeme**

### CODE REVIEW

**Comment by GuiLeme** [comment]
Nevermid, I mistook the PR target, sorry

**Comment by otacke** [comment]
Are you trying to pack an H5P library? The H5P CLI tool already has a command for that job: `h5p pack` in the pinned version that I am still using, `h5p utils pack` in the latest release that I am not referencing yet (waiting for the next release with some changes to translation handling).

**Comment by GuiLeme** [comment]
Hey, Oliver, thanks for the comment. Yes, that is exactly what I'm trying to do, basically, I want to have the package already in the release tag page of Github! Thanks for the command, I will try that out!

**Comment by otacke** [comment]
Then indeed that's what you'd use the H5P CLI tool's `pack` command for. You can also let yourself inspire from https://github.com/boyum/pack-h5p-action

The issue here is that you'd be packing the single library only, but its dependencies would still be missing. May be what you want, might not be as well. And automated collection of dependencies from github would require you to make sure to grab the latest release version, or otherwise you'd ship development versions.

**Comment by GuiLeme** [comment]
Hum, I don't think I would need the dependencies. See, my final goal, is to have a tarball of all the libraries I need for some content-types (In my case, I want the drag and drop and crossword activities for now), this way, I will be able to simply unpack the tarball into a server, and use the activities right away with a `content.json` (this is the context of the Bigbluebutton integration), so ultimately, I would have the h5p-plugin dependencies installed within a BBB server out-of-the-box (at least for the two activities I mentioned).

I don't know if I am following the right path for achieving it, so if you have any tips for this, I'd appreciate it very much. I'm also able to email you with some more details, if needed.

**Comment by otacke** [comment]
But if you want to have all libraries needed for some content type, you will need to take care of dependencies, so e.g.
H5P.DragQuestion
\_H5P.JoubelUI
  jQuery.ui
  H5P.Question
  H5PEditor.DragQuestion
  H5PEditor.RangeList
  H5PEditor.ShowWhen

- and these are only the direct children, some of them have dependencies themselves.

The cleanest way probably would be to query the Hub server on h5p.org like H5P integrations would and fetch all the release versions from there regularly. If you have your own repositories with your own content types, that will not work however, sure.

**Pull request closed without merging**
