### PR TITLE
Update and rename .en.json to ko.json

### PR DESCRIPTION
**Pull request by totoromaum**
Hi, I'm glad to contribute to this translation.

### CODE REVIEW

**Review by otacke — CHANGES_REQUESTED** [review]
Hi @totoromaum 
Thanks for your contribution! The translation itself is fine. However, the .en.json needs to stay.
Please, instead of renaming it to ko.json, create a copy and rename that one before you make your changes (or now put .en.json back into your pull request by adding a new commit to your branch that the pull request is based on).

**Comment by totoromaum** [comment]
Hi, @otacke, I hope you have a great day. I made a new commit, but I find that I am able to commit it to the master branch ahead of you. I hope this is fine. Thank you.

**Comment by otacke** [comment]
@totoromaum Thanks! You have now made a commit to your master branch instead of committing to your patch-1 branch. If you want me to merge from your master branch, you'll have to create a new pull request based on that branch. If you want me to merge in this pull request, you'd have to add the .en.json file back your patch-1 branch and commit it. This pull request will then get amended automatically.

**Comment by totoromaum** [comment]
@otacke , hi, Otacke, I hope that you have a great day. I am eager to make any changes to make a right commit, but I find I am not familiar enough to Github. Could you kindly guide me how to commit the translation to the right place? Could you suggest an easier solution?

**Comment by otacke** [comment]
Hi @totoromaum You're using github alone, not git? I see. You'd have to switch to your `patch-1` branch by using the selector in the upper left corner and that should be labelled `master` by default. There you would click on "Add file" and put the original `.en.json` file back into the branch by committing. That's should be enough.

May I suggest to register at https://translate-h5p.tk/ and familiarize yourself with that platform? It makes contributing translations to H5P much easier and less prone to errors.

**Comment by totoromaum** [comment]
@otacke, thank you for explaining it in detail and introducing the translation platform. I will use it next time. By the way, I tried to follow your instruction and added an .en.json file, but I am not sure if I did it correctly because I just created a new .en.json file rather than putting back the original .en.json file to the place. Please let me know if I take a different steps. Thank you!

**Review by otacke — APPROVED** [review]
@totoromaum Thanks!

If you look at https://github.com/otacke/h5p-crossword/pull/2/files now, you will notice that it lists just one file as changed. That's because git(hub) noticed that the new file that you added was completely identical to the original one. So, in total your pull request is as if you only added the ko.json file. Well, it's two commits now, but not a problem.

Best,
Oliver

**Comment by totoromaum** [comment]
@otacke Thank you. Have a great one!

**Pull request merged**
