### PR TITLE
Translations update from Translate H5P

### PR DESCRIPTION
**Pull request by translate-h5p**
Translations update from [Translate H5P](https://translate-h5p.tk) for [H5P/h5p-crossword](https://translate-h5p.tk/weblate/projects/h5p/h5p-crossword/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by otacke — CHANGES_REQUESTED** [review]
That doesn't feel right:
https://github.com/otacke/h5p-crossword/blob/1f910a657c0ade0a79bfff52c4302ff2a4759f78/language/cs.json#L74-L84

**Comment by sr258** [comment]
@otacke It's a new Weblate plugin that prefills all empty translation strings with the English source strings to avoid these super annoying intermediate pushs that you can't accept. That way the user experience will never be affected by half-finished translations.

**Comment by sr258** [comment]
@otacke Or do you mean that the semantics are incorrect?

**Comment by otacke** [comment]
@sr258 But why would there be two consecutive entries for "Feedback for defined score range"?

The block in semantics is
```
            {
              "name": "from",
              "type": "number",
              "label": "Score Range",
              "min": 0,
              "max": 100,
              "default": 0,
              "unit": "%"
            },
            {
              "name": "to",
              "type": "number",
              "min": 0,
              "max": 100,
              "default": 100,
              "unit": "%"
            },
            {
              "name": "feedback",
              "type": "text",
              "label": "Feedback for defined score range",
              "importance": "low",
              "placeholder": "Fill in the feedback",
              "optional": true
            }
```

which yields

```
              {
                "label": "Score Range"
              },
              {},
              {
                "label": "Feedback for defined score range",
                "placeholder": "Fill in the feedback"
              }
```
in .en.json, and this pull request suggests:

```
              {
                "label": "Score Range"
              },
              {
                "label": "Feedback for defined score range",
                "placeholder": "Fill in the feedback"
              },
              {
                "label": "Feedback for defined score range",
                "placeholder": "Fill in the feedback"
              }
```

Some misalignment?

**Comment by sr258** [comment]
I see, looks like Weblate doesn't generate the correct JSON structure for empty entries. I don't believe this was the case before, so this might be a bug in the new addon or some other bug introduced recently. I'll create an issue in the Weblate issue tracker.

**Comment by sr258** [comment]
I've opened the issue at https://github.com/WeblateOrg/weblate/issues/7201

**Comment by otacke** [comment]
@sr258 👍

**Pull request merged**
